/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./components/AboutModal.vue')['default']
    AColorPicker: typeof import('@arco-design/web-vue')['ColorPicker']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    IconBgColors: typeof import('@arco-design/web-vue/es/icon')['IconBgColors']
    IconBtn: typeof import('./components/IconBtn.vue')['default']
    LineFormModal: typeof import('./components/LineFormModal.vue')['default']
    MapBox: typeof import('./components/MapBox.vue')['default']
    MapLogo: typeof import('./components/MapLogo.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    PointFormModal: typeof import('./components/PointFormModal.vue')['default']
    PolygonFormModal: typeof import('./components/PolygonFormModal.vue')['default']
    SourceBar: typeof import('./components/SourceBar.vue')['default']
    SourceDrawData: typeof import('./components/SourceDrawData.vue')['default']
    SourceTiffData: typeof import('./components/SourceTiffData.vue')['default']
    TfwBtn: typeof import('./components/TfwBtn.vue')['default']
    TifBtn: typeof import('./components/TifBtn.vue')['default']
    TiffBtn: typeof import('./components/TiffBtn.vue')['default']
    Titlebar: typeof import('./components/Titlebar.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    ToolBtn: typeof import('./components/ToolBtn.vue')['default']
  }
}
